### PR TITLE
Avoid publishing unhandled sequence keys as keyspace operations.

### PR DESCRIPTION
**Pull request by wearhere**
Servers should not observe each others' sequence keys, and doing so previously caused
the keys to be fired as keyspace operations, which triggered an error in
`keyspace_notification_observe_driver.js` about not handling the sequence "operation".

### CODE REVIEW

**Comment by Slava** [comment]
thanks, merged!

**Comment by wearhere** [comment]
Thanks for the speedy response! Mind bumping the package version too? Then we can get rid of our submodule.

**Comment by Slava** [comment]
Will do

**Comment by wearhere** [comment]
Thanks!

**Pull request merged**
